apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
      version: 1.4.4
  interval: 15m
  values:
    service:
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics-path: "/metrics"
        k8s.grafana.com/portName: "http"
        k8s.grafana.com/metrics-scheme: "http"
    persistence:
      enabled: false
    serviceMonitor:
      enabled: true
    config:
      storage:
        type: memory
      metrics: true
      endpoints:
        - name: Personal
          group: Projects
          url: https://j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: Blog
          group: Projects
          url: https://blog.j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: kube-cats
          group: Projects
          url: https://meow.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: kube-cats-api
          group: Projects
          url: https://kube-cats-api.j6n.dev/health
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == OK"
        - name: Jellyfin
          group: Media
          url: https://watch.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: Jellyseerr
          group: Media
          url: https://requests.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: Photos
          group: Media
          url: https://photos.j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: Gatus
          group: Observability
          url: https://status.j6n.dev/health
          conditions:
            - "[STATUS] <= 299"
            - "[BODY].status == UP"
        - name: Grafana
          group: Observability
          url: https://grafana.j6n.dev/api/health
          conditions:
            - "[STATUS] <= 299"
            - "[BODY].database == ok"
        - name: AlertManager
          group: Observability
          url: http://vmalertmanager-vmks-victoria-metrics-k8s-stack.observability:9093/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == OK"
        - name: VictoriaMetrics - Alert
          group: Observability
          url: http://vmalert-vmks-victoria-metrics-k8s-stack.observability:8080/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == VictoriaMetrics is Healthy."
        - name: VictoriaMetrics - Agent
          group: Observability
          url: http://vmagent-vmks-victoria-metrics-k8s-stack.observability:8429/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == VictoriaMetrics is Healthy."
        - name: VictoriaMetrics - Insert
          group: Observability
          url: http://vminsert-vmks-victoria-metrics-k8s-stack.observability:8480/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == VictoriaMetrics is Healthy."
        - name: VictoriaMetrics - Select
          group: Observability
          url: http://vmselect-vmks-victoria-metrics-k8s-stack.observability:8481/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == VictoriaMetrics is Healthy."
        - name: VictoriaMetrics - Storage
          group: Observability
          url: http://vmstorage-vmks-victoria-metrics-k8s-stack.observability:8482/-/healthy
          conditions:
            - "[STATUS] <= 299"
            - "[BODY] == VictoriaMetrics is Healthy."
        - name: Actual
          group: Tools
          url: https://actual.j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: Authentik
          group: Tools
          url: https://auth.j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: HomeAssistant
          group: Tools
          url: https://hass.j6n.ca
          conditions:
            - "[STATUS] <= 299"
        - name: Moodist
          group: Utilities
          url: https://moodist.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: IT-Tools
          group: Utilities
          url: https://tools.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: Vert
          group: Utilities
          url: https://convert.j6n.dev
          conditions:
            - "[STATUS] <= 299"
        - name: YoPass
          group: Utilities
          url: https://secrets.j6n.dev
          conditions:
            - "[STATUS] <= 299"
