# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-internal
  annotations:
    gatus.home-operations.com/enabled: "true"
    # sidecar defaults HTTPRoutes to https; envoy-internal is http-only
    gatus.home-operations.com/endpoint: |
      group: observability
      url: http://gatus.j6n.internal
spec:
  parentRefs:
  - name: envoy-internal
    namespace: network
  hostnames:
  - gatus.j6n.internal
  rules:
  - backendRefs:
    - name: gatus
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-external
  annotations:
    # group: external inherited from the envoy-external gateway
    gatus.home-operations.com/enabled: "true"
spec:
  parentRefs:
  - name: envoy-external
    namespace: network
  hostnames:
  - status.j6n.dev
  rules:
  - backendRefs:
    - name: gatus
      port: 80
