apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository:	ghcr.io/recyclarr/recyclarr
              tag: 7.5.2
            env:
              CRON_SCHEDULE: "@daily"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: *port
                name: http
                protocol: TCP

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
      
    persistence:
      config:
        globalMounts:
          - path: /config
            readOnly: false
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 500Mi
        accessMode: ReadWriteOnce
      tmp:
        type: emptyDir
