apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-logs
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/victoria-logs/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-logs-storage
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: *app
  dependsOn:
    - name: victoria-logs-cluster
  interval: 5m
  path: ./apps/base/victoria-logs/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
