apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app csi-driver-nfs
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      version: 4.12.1
  interval: 15m
  values:
