---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        GRAFANA_USERNAME: "{{ .admin_user }}"
        GRAFANA_PASSWORD: "{{ .admin_password }}"

  data:
    - secretKey: admin_user
      remoteRef:
        key: grafana-admin
        property: username
    - secretKey: admin_password
      remoteRef:
        key: grafana-admin
        property: password
