---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 30m
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.6.0
