apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mc-router
  namespace: flux-system
spec:
  interval: 5m
  ref:
    tag: 1.4.0
  url: oci://ghcr.io/itzg/minecraft-server-charts/mc-router
