apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 5m
  ref:
    tag: 5.0.0
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
