---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: toolhive-operator
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator
  ref:
    tag: 0.19.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator-crds
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: 0.19.0
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds

