---
# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app getbud
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: ctrl-research
        namespace: flux-system
      version: 0.2.2
  dependsOn: []
  interval: 15m
  values:
    deployments:
      app:
        image:
          registry: ghcr.io
          repository: ctrl-research/getbud
          tag: 0.0.1
          pullPolicy: IfNotPresent

        containerName: *app

        env:
          - name: TZ
            value: America/Toronto
          - name: GETBUD_ADDR
            value: ":8080"
          - name: GETBUD_BASE_URL
            value: https://budget.j6n.dev
          - name: GETBUD_LOCAL_AUTH
            value: "false"

        envFrom:
          - secretRef:
              name: *app

        ports:
          - containerPort: 8080
            name: http
            protocol: TCP

        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http

        resources:
          requests:
            cpu: 10m

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

        podSecurityContext:
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000

        volumes:
          - name: tmp
            emptyDir: {}

        volumeMounts:
          - name: tmp
            mountPath: /tmp

    services:
      app:
        type: ClusterIP
        ports:
          - port: 8080
            targetPort: http
            protocol: TCP
            name: http
