apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellystat
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: cyfershepard/jellystat
              tag: 1.1.6
            env:
              POSTGRES_IP: "media-postgres-rw"
              POSTGRES_PORT: "5432"
              POSTGRES_USER: "{{ .Release.Name }}"
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              POSTGRES_DB: "{{ .Release.Name }}"
              LOG_LEVEL: "info"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: &port 3000
                name: http
                protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port          
