---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        JWT_SECRET: "{{ .jwt }}"
        JS_USER: "{{ .username }}"
        JS_PASSWORD: "{{ .password }}"

  data:
  - secretKey: username
    remoteRef:
      key: romm-secret
      property: username
  - secretKey: password
    remoteRef:
      key: romm-secret
      property: password
  - secretKey: jwt
    remoteRef:
      key: romm-secret
      property: jwt
