apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app romm
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      romm:
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: 4.4.1
            env:
              DB_HOST: romm-postgres-rw
              DB_PORT: 5432
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: username
              DB_PASSWD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              DB_NAME: "{{ .Release.Name }}"
              LOG_LEVEL: "info"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: &port 8080
                name: http
                protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: configMap
        name: romm-config
        globalMounts:
          - path: /romm/config/config.yml
            subPath: config.yml
            readOnly: true
      library:
        type: nfs
        server: nasj6n.home
        path: /volume2/kubernetes/gaming/romm/library
        globalMounts:
          - path: /romm/library
      
      tmp:
        type: emptyDir
