apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app romm
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      romm:
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: 4.4.1
            env:
              DB_HOST: romm-postgres-rw
              DB_PORT: 5432
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: username
              DB_PASSWD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              DB_NAME: "{{ .Release.Name }}"
              DISABLE_DOWNLOAD_ENDPOINT_AUTH: true
              DISABLE_USERPASS_LOGIN: false
              ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"
              ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP: "true"
              ENABLE_SCHEDULED_RESCAN: "true"
              ENABLE_SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC: "true"
              ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA: "true" #chron set to 5m by default
              ENABLE_SCHEDULED_UPDATE_MAME_XML: "false"
              ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB: "false"
              HASHEOUS_API_ENABLED: true
              PLAYMATCH_API_ENABLED: true
              REDIS_HOST: "{{ .Release.Name }}-dragonfly"
              REDIS_PORT: "6379"
              RESCAN_ON_FILESYSTEM_CHANGE_DELAY: 5
              ROMM_BASE_PATH: /romm
              ROMM_DB_DRIVER: postgresql
              SCHEDULED_RESCAN_CRON: "0 3 * * *"
              LAUNCHBOX_API_ENABLED: "true"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: &port 8080
                name: http
                protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: configMap
        name: romm-config
        globalMounts:
          - path: /romm/config/config.yml
            subPath: config.yml
            readOnly: true
      library:
        type: nfs
        server: nasj6n.home
        path: /volume2/kubernetes/gaming/romm/library
        globalMounts:
          - path: /romm/library
      
      tmp:
        type: emptyDir
