---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        API_KEY: "{{ .api_key }}"

  data:
  - secretKey: api_key
    remoteRef:
      key: jellyseerr-jellyfin
      property: api_key
