apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflare-tunnel
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      version: 0.3.2
  interval: 15m
  values:
    cloudflare:
      tunnelName: "k8s-lab"
      # If defined, no secret is created for the credentials, and instead, the secret referenced is used
      secretName: cloudflare-tunnel-credentials
      # If true, turn on WARP routing for TCP
      enableWarp: true
      # Define ingress rules for the tunnel. See
      # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
      ingress:
        - hostname: gatus.j6n.dev
          service: http://gatus.gatus.svc.cluster.local:80
        - hostname: grafana.j6n.dev
          service: http://grafana.grafana.svc.cluster.local:80
    replicaCount: 1
        