apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: media-postgres
spec:
  instances: 3
  managed:
    roles:
      - name: jellyfin
        login: true
        passwordSecret:
          name: jellyfin-postgres
  storage:
    storageClass: longhorn
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellyfin-postgres
spec:
  cluster: 
    name: media-postgres
  name: &app jellyfin
  owner: *app
---
