apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: media-postgres
spec:
  instances: 3
  managed:
    roles:
      - name: jellyseerr
        login: true
        passwordSecret:
          name: jellyseerr-postgres
      - name: jellystat
        login: true
        passwordSecret:
          name: jellystat-postgres
      - name: sonarr
        login: true
        passwordSecret:
          name: sonarr-postgres
      - name: radarr
        login: true
        passwordSecret:
          name: radarr-postgres
  storage:
    storageClass: longhorn
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellyseerr-postgres
spec:
  cluster: 
    name: media-postgres
  name: &app jellyseerr
  owner: *app
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellystat-postgres
spec:
  cluster: 
    name: media-postgres
  name: &app jellystat
  owner: *app
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-postgres
spec:
  cluster: 
    name: media-postgres
  name: &app sonarr
  owner: *app
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-postgres
spec:
  cluster: 
    name: media-postgres
  name: &app radarr
  owner: *app
---
