{
 "title": "Gatus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {
     "query": "label_values(gatus_results_total,group)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(gatus_results_total{group=~\"$group\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "endpoint" },
  {
   "title": "✅ Results",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (success) (rate(gatus_results_total{group=~\"$group\", name=\"$endpoint\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⌛ Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gatus_results_duration_seconds{group=~\"$group\", name=\"$endpoint\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "avg_over_time(gatus_results_duration_seconds{group=~\"$group\", name=\"$endpoint\"}[1d])",
     "legendFormat": "Last 1d"
    }
   ]
  },
  {
   "title": "📉 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gatus_results_duration_seconds{group=~\"$group\", name=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏱️ Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{group=~\"$group\", name=~\"$endpoint\", success=\"true\"}[1d]))\r\n/\r\nsum(rate(gatus_results_total{group=~\"$group\", name=~\"$endpoint\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📜 Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_certificate_expiration_seconds{group=~\"$group\", name=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}