apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  targetNamespace: authentik
  commonMetadata:
    labels:
      service: authentik
  interval: 5m
  path: ./apps/base/authentik/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
