apiVersion: v1
kind: ConfigMap
metadata:
  name: &app bifrost
data:
  config.json: |
    {
      "providers": {
        "local": {
          "network_config": {
            "base_url": "http://jarvis.home:13305/v1"
          }
        },
        "minimax": {
          "keys": [
            {
              "name": "minimax-key",
              "value": "env.MINIMAX_API_KEY",
              "models": ["MiniMax-2.7"],
              "weight": 1.0
            }
          ],
          "network_config": {
            "base_url": "https://api.minimax.chat/v1"
          }
        },
        "hermes-agent": {
          "keys": [
            {
              "name": "hermes-agent-key",
              "value": "env.HERMES_AGENT_API_KEY",
              "models": ["*"],
              "weight": 1.0
            }
          ],
          "network_config": {
            "base_url": "http://hermes-agent-app.hermes-agent:8642/v1"
          }
        }
      }
    }
