apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bifrost
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      version: v2.0.16
  interval: 15m
  commonMetadata:
    labels:
      service: *app
  values:
    image:
      tag: v1.4.20
    storage:
      persistence:
        size: 1Gi
    envFrom:
      - secretRef:
          name: *app
    bifrost:
      providers:
        minimax:
          keys:
            - name: "minimax-key"
              value: "env.MINIMAX_API_KEY"
              models: ["MiniMax-2.7"]
              weight: 1
          network_config:
            base_url: https://api.minimax.chat/v1
        local:
          keys:
            - name: "local-key"
              value: ""
              weight: 1
          network_config:
            base_url: http://jarvis.home:13305/v1
        hermes-agent:
          keys:
            - name: "hermes-agent-key"
              value: "env.HERMES_AGENT_API_KEY"
              weight: 1
          network_config:
            base_url: http://hermes-agent-app.hermes-agent:8642/v1
        