apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: &app cloudflare-tunnel 
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    path: /metrics
    scheme: http
    scrapeTimeout: 30s
  jobLabel: *app
  namespaceSelector:
    matchNames:
    - *app
  selector:
    matchLabels:
      app.kubernetes.io/instance: *app
      app.kubernetes.io/name: *app
