apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: 2025.8.4
  interval: 15m
  values:
    # Disable dep charts
    redis:
      enabled: false
    postgresql:
      enabled: false
    global:
      env:
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__USER
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: password
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-config
              key: secretkey
    authentik:
      redis:
        host: authentik-dragonfly
      postgresql:
        host: authentik-postgres-rw
    server:
      autoscaling:
        enabled: true
        minReplicas: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    prometheus:
      rules:
        enabled: true
        namespace: observability
