# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: ${APP}-dragonfly
spec:
  selector:
    matchLabels:
      app: ${APP}-dragonfly
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
