---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .apikey }}"

  data:
  - secretKey: apikey
    remoteRef:
      key: sonarr-secret
      property: apikey
