apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: linuxserver/sonarr
              tag: 4.0.16
            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__APP__THEME: dark
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__POSTGRES__HOST: "media-postgres-rw"
              SONARR__POSTGRES__MAINDB: "{{ .Release.Name }}"
              SONARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              SONARR__POSTGRES__PORT: "5432"
              SONARR__POSTGRES__USER: "{{ .Release.Name }}"
              SONARR__SERVER__PORT: &port 8989
              SONARR__UPDATE__BRANCH: develop
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: *port
                name: http
                protocol: TCP

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
      
    persistence:
      config:
        globalMounts:
          - path: /config
            readOnly: false
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
      media:
        type: nfs
        server: nasj6n.home
        path: /volume2/kubernetes/media/data
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
