apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: linuxserver/prowlarr
              tag: 2.3.2
            env:
              TZ: America/Toronto
              PROWLARR__APP__INSTANCENAME: "{{ .Release.Name }}"
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
              PROWLARR__POSTGRES__HOST: "media-postgres-rw"
              PROWLARR__POSTGRES__MAINDB: "{{ .Release.Name }}"
              PROWLARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              PROWLARR__POSTGRES__PORT: "5432"
              PROWLARR__POSTGRES__USER: "{{ .Release.Name }}"
              PROWLARR__SERVER__PORT: &port 9696
              PROWLARR__UPDATE__BRANCH: develop
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: *port
                name: http
                protocol: TCP
        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.3
            envFrom:
              - secretRef:
                  name: "gluetun-secret"
            securityContext:
              capabilities:
                add: ["NET_ADMIN"]
            # Keep gluetun running for the duration of the pod
            restartPolicy: Always

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
      
    persistence:
      config:
        globalMounts:
          - path: /config
            readOnly: false
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 500Mi
        accessMode: ReadWriteOnce
      gluetun:
        type: emptyDir
      tmp:
        type: emptyDir
