apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: preview-OIDC
            env:
              DB_TYPE: "postgres"
              DB_HOST: "media-postgres-rw"
              DB_PORT: "5432"
              DB_USER: "{{ .Release.Name }}"
              DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              DB_NAME: "{{ .Release.Name }}"
              LOG_LEVEL: "info"
              PORT: &port 5055
              TZ: America/Toronto
            # envFrom:
            #   - secretRef:
            #       name: "{{ .Release.Name }}-secret"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        globalMounts:
          - path: /app/config
            readOnly: false
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 1Gi
        accessMode: ReadWriteOnce
      tmp:
        type: emptyDir            
