---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-postgres
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: authentik-postgres
  podMetricsEndpoints:
  - port: metrics
