---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-unas
provisioner: nfs.csi.k8s.io
parameters:
  server: mimir.home
  share: /MEDIA
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=16
  - hard
  - noatime
