apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"

  data:
  - secretKey: client_id
    remoteRef:
      key: grafana-oidc
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: grafana-oidc
      property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        admin_user: "{{ .admin_user }}"
        admin_password: "{{ .admin_password }}"

  data:
  - secretKey: admin_user
    remoteRef:
      key: grafana-admin
      property: username
  - secretKey: admin_password
    remoteRef:
      key: grafana-admin
      property: password
