apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-metrics-operator
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
      version: 0.60.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  interval: 15m
  values:
    crds:
      plain: true
    serviceMonitor:
      enabled: true
