apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: linuxserver/radarr
              tag: 6.0.4
            env:
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__POSTGRES__HOST: "media-postgres-rw"
              RADARR__POSTGRES__MAINDB: "{{ .Release.Name }}"
              RADARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: password
              RADARR__POSTGRES__PORT: "5432"
              RADARR__POSTGRES__USER: "{{ .Release.Name }}"
              RADARR__SERVER__PORT: &port 7878
              RADARR__UPDATE__BRANCH: develop
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            ports:
              - containerPort: *port
                name: http
                protocol: TCP

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
      
    persistence:
      config:
        globalMounts:
          - path: /config
            readOnly: false
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 500Mi
        accessMode: ReadWriteOnce
      media:
        type: nfs
        server: nasj6n.home
        path: /volume2/kubernetes/media/data
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
