apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics-operator
  namespace: flux-system
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/victoria-metrics-operator/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
