apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ${APP}-dragonfly
spec:
  selector:
    matchLabels:
      app: ${APP}-dragonfly
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
