apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: gatus
  dependsOn:
    - victoria-metrics
    - grafana-operator
  interval: 5m
  path: ./apps/base/flux/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
