apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  dependsOn:
    - name: snapshot-controller
  commonMetadata:
    labels:
      service: longhorn
  interval: 5m
  path: ./apps/base/longhorn/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-dashboards
  namespace: flux-system
spec:
  targetNamespace: observability
  dependsOn:
    - name: grafana-operator
  commonMetadata:
    labels:
      service: longhorn
  interval: 5m
  path: ./apps/base/longhorn/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
