apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karma
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      karma:
        containers:
          app:
            image:
              repository: ghcr.io/prymitive/karma
              tag: v0.122
            env:
              CONFIG_FILE: "/config/karma.yaml"
              LOG_LEVEL: "info"
              TZ: America/Toronto
            ports:
              - containerPort: &port 8080
                name: http
                protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        globalMounts:
          - path: /config
            readOnly: false
      tmp:
        type: emptyDir
