# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: karma-config
    files:
      - karma.yaml=./config/karma.yaml
generatorOptions:
  disableNameSuffixHash: true
