apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app goldpinger
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      version: 1.0.1
  interval: 15m
  # values.yaml
  values:
