apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hypermind
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      karma:
        containers:
          app:
            image:
              repository: ghcr.io/lklynet/hypermind
              tag: 1.0.1
            env:
              PORT: 3000
              ENABLE_CHAT: "true"
              ENABLE_MAP: "true"
              LOG_LEVEL: "info"
              TZ: America/Toronto
            ports:
              - containerPort: &port 3000
                name: http
                protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port
