apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app karpor
  namespace: flux-system
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/karpor/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
