apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      service: metrics-server
  interval: 5m
  path: ./apps/base/metrics-server/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
