apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app spegel
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  interval: 15m
  values:
    grafanaDashboard:
      enabled: true
      mode: GrafanaOperator
      grafanaOperator:
        matchLabels:
          dashboards: homelab
        folder: System
    serviceMonitor:
      enabled: false
