apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  commonMetadata:
    labels:
      service: cnpg
  interval: 5m
  path: ./apps/base/cloudnative-pg/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-monitoring
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: cnpg
  dependsOn:
    - name: grafana-operator
  interval: 5m
  path: ./apps/base/cloudnative-pg/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
