apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: &app spegel
spec:
  endpoints:
  - interval: 60s
    port: metrics
    scrapeTimeout: 30s
  jobLabel: *app
  namespaceSelector:
    matchNames:
    - kube-utils
  selector:
    matchLabels:
      app.kubernetes.io/instance: *app
      app.kubernetes.io/name: *app
      app.kubernetes.io/component: metrics
