apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: gatus
  dependsOn:
    - name: victoria-metrics
    - name: grafana-operator
  interval: 5m
  path: ./apps/base/flux-system/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-operator
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/flux-system/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-instance
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      service: *app
  dependsOn:
    - name: flux-operator
  interval: 5m
  path: ./apps/base/flux-system/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
