apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  interval: 15m
