apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kube-cats
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: j6nca
        namespace: flux-system
      version: 1.0.8
  interval: 15m
  commonMetadata:
    labels:
      service: *app
