apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: flux-system
  interval: 15m
  values:
    serviceMonitor:
      enabled: false
    grafanaDashboard:
      enabled: true
      folder: databases
      # -- Grafana dashboard configmap annotations.
      annotations:
        name: grafana_folder
      # -- Grafana dashboard configmap labels
      labels:
        name: grafana_dashboard
      grafanaOperator:
        enabled: true
        allowCrossNamespaceImport: true
        # -- Selected labels for Grafana instance
        matchLabels:
          dashboards: homelab
