{
 "title": "Gatus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {
     "query": "label_values(gatus_results_total,group)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(gatus_results_total{group=~\"$group\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "endpoint" },
  {
   "title": "$endpoint results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (success) (gatus_results_total{group=~\"$group\", name=\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_duration_seconds{group=~\"$group\", name=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Cert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatus_results_certificate_expiration_seconds{group=~\"$group\", name=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}