---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .github_token }}"

  data:
    - secretKey: github_token
      remoteRef:
        key: openclaw-gh
        property: pat
