apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-dns
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/external-dns/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---

