apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 3
  managed:
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: authentik-postgres
  storage:
    storageClass: longhorn
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik-postgres
spec:
  cluster: 
    name: authentik-postgres
  name: &app authentik
  owner: *app
---
