apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app media-storage
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/media/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  dependsOn:
    - name: media-storage
  interval: 5m
  path: ./apps/base/media/jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyseerr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  dependsOn:
    - name: media-storage
  interval: 5m
  path: ./apps/base/media/jellyseerr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellystat
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/media/jellystat
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
