apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app media-storage
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/media/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app media
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/media/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
