apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vmks
spec:
  sourcePVC: vmcluster-victoria-metrics-k8s-stack
  trigger:
    # Run backup daily @ midnight
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 7
    # Name of secret with bucket config
    repository: vmks-replication
    # Backup retention policy
    retain:
      daily: 7
    # Use Snapshot method for longhorn
    copyMethod: Snapshot
