apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cobblemon-academy
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2025.12.0@sha256:4eb78cc5f3f4e87e281d38590deca2a4a74afaa9f351210059cb2786443994f2
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1000m
        memory: 6Gi
      limits:
        cpu: 2000m
        memory: 9Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    livenessProbe:
      initialDelaySeconds: 30
    readinessProbe:
      initialDelaySeconds: 30
    startupProbe:
      enabled: true
    extraEnv:
      TZ: America/Toronto
    persistence:
      dataDir:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        Size: 15Gi
        accessModes:
          - ReadWriteOnce
    minecraftServer:
      serviceType: NodePort
      ## Set the port used if the serviceType is NodePort
      nodePort: 30002
      eula: true
      version: 1.21.1
      ## The type of Minecraft server to run, check for related settings below
      ## Common types: "VANILLA", "FABRIC", "FORGE", "SPIGOT", "BUKKIT", "PAPER",
      ## "FTBA", "SPONGEVANILLA", "AUTO_CURSEFORGE"
      ## ref: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms
      type: AUTO_CURSEFORGE
      # Optional URI to a resource pack. The player may choose to use it.
      resourcePackUrl:
      # Optional SHA-1 digest of the resource pack, in lowercase hexadecimal.
      # It is recommended to specify this, because it is used to verify the integrity of the resource pack.
      resourcePackSha:
      # When true, players will be prompted for a response and will be disconnected if they decline the required pack
      resourcePackEnforce: false
      overrideServerProperties: true
      memory: 7168M
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      whitelist: "turtlescute"
      ops: "turtlescute"
      motd: "Cobblemon Academy Server"
      worldSaveName: world
      viewDistance: 12
      levelSeed: "cobblemonacademy"
      rcon:
        enabled: true
        existingSecret: minecraft-cobblemon-academy-secret
        secretKey: rcon_password
      autoCurseForge:
        # CurseForge API key obtained from developer console
        apiKey:
          existingSecret: minecraft-cobblemon-academy-secret
          secretKey: CF_API_KEY
        # Link to modpack in general or a specific file
        # NOTE: In case of specific file - do not point at server file
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/cobblemon-academy-2-0"

      # These options allow you to expose another port from the Minecraft server, plugins such
      # as dynmap (8123) and bluemap (8100) will require this for access to their web interfaces
      # extraPor
