# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus-snmp-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/prometheus-snmp-exporter/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
