apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: flux-system
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      service: *app
  dependsOn:
    - name: open-webui-data
  interval: 5m
  path: ./apps/base/llm/open-webui/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui-data
  namespace: flux-system
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/llm/open-webui/data
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
