apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  targetNamespace: volsync
  commonMetadata:
    labels:
      service: volsync
  dependsOn:
    - name: external-secrets-resources
    - name: snapshot-controller
  interval: 5m
  path: ./apps/base/volsync/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-dashboards
  namespace: flux-system
spec:
  targetNamespace: observability
  dependsOn:
    - name: grafana-operator
  commonMetadata:
    labels:
      service: volsync
  interval: 5m
  path: ./apps/base/volsync/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
