apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        # OAUTH CONFIG
        ENABLE_OAUTH_SIGNUP: "true"
        ENABLE_OAUTH_PERSISTENT_CONFIG: "false"
        OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
        OAUTH_PROVIDER_NAME: Authentik
        OPENID_PROVIDER_URL: https://auth.j6n.dev/application/o/open-webui/.well-known/openid-configuration
        OAUTH_SCOPES: openid email profile
        OPENID_REDIRECT_URI: https://chat.j6n.dev/oauth/oidc/callback
        OAUTH_CLIENT_ID: "{{ .client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: open-webui-oidc
