apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn: []
  interval: 15m
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.8.5@sha256:2deb90b0423473d8f97febced2e62b8fd898aa3eb61877bb3aa336370214c258
            env:
              # Image Generation
              ENABLE_OPENAI_API: False
              ENABLE_OLLAMA_API: True
              # Enable once comfy-ui is ready
              ENABLE_IMAGE_GENERATION: False
              # IMAGE_GENERATION_ENGINE: comfyui
              # IMAGE_GENERATION_MODEL: dreamshaper_8
              # IMAGE_SIZE: 400x400
              # IMAGE_STEPS: 8
              # COMFYUI_BASE_URL: 
              # Open-webui settings
              OLLAMA_BASE_URL: http://ollama.ollama:11434
              # Enable once searxng is ready
              ENABLE_RAG_WEB_SEARCH: false
              ENABLE_SEARCH_QUERY: false
              # RAG_WEB_SEARCH_ENGINE: searxng
              # SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
              # Enable redis for scaling
              # ENABLE_WEBSOCKET_SUPPORT: "true"
              # WEBSOCKET_MANAGER: "redis"
              # WEBSOCKET_REDIS_URL: "redis://{{ .Release.Name }}-dragonfly:6379"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
              - secretRef:
                  name: "{{ .Release.Name }}-postgres"
            resources:
              requests:
                cpu: 500m
              limits:
                memory: 2Gi
            ports:
              - containerPort: &port 8080
                name: http
                protocol: TCP
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /app/backend/data
