apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmks
spec:
  chart:
    spec:
      chart: &app victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
      version: 0.60.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  interval: 15m
  values:
    # Disable VMSingle and create VMCluster
    vmsingle:
      enabled: false
    vmcluster:
      enabled: true
      spec:
        vmagent:
          enabled: false
        vmstorage:
          enabled: true
          replicaCount: 2
          storageDataPath: /vm-data
          storage:
            volumeClaimTemplate:
              spec:
                storageClassName: longhorn
                resources:
                  requests:
                    storage: 15Gi

    # Deploy operator separately
    victoria-metrics-operator:
      enabled: false
    # Deploy grafana separately
    grafana:
      enabled: false
    # Include dashboards from chart
    defaultDashboards:
      enabled: true
