apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        # Discord
        # GH
        GITHUB_PAT: "{{ .gh_pat }}"
        # Other
        OLLAMA_URL: jarvis.home:11434
        # OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
  data:
  - secretKey: gh_pat
    remoteRef:
      key: openclaw-gh
      property: pat
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app openclaw-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      data:
        openclaw.json: | 
          {
            auth: {
              profiles: {
                "minimax:default": {
                  "provider": "minimax",
                  "mode": "api_key"
                }
              }
            },
            models: {
              mode: "merge",
              providers: {
                "ollama": {
                  baseUrl: "http://jarvis.home:8000/",
                  apiKey: "ollama",
                  api: "openai-completions",
                  models: [
                    { id: "Qwen3-Coder-Next-GGUF", name: "Qwen3-Coder-Next-GGUF", reasoning: false, input: ["text"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 8192 },
                  ]
                },
                "minimax": {
                  baseUrl: "https://api.minimax.io/anthropic",
                  apiKey: "{{ .MINIMAX_API_KEY }}",
                  api: "anthropic-messages",
                  models: [
                    { id: "MiniMax-M2.7", name: "MiniMax M2.7", reasoning: false, input: ["text"], cost: { input: 15, output: 60, cacheRead: 2, cacheWrite: 10 }, contextWindow: 1000000, maxTokens: 32768, },
                    { id: "MiniMax-VL-01", name: "MiniMax VL-01", reasoning: false, input: ["text", "image"], cost: { input: 15, output: 60, cacheRead: 2, cacheWrite: 10 }, contextWindow: 1000000, maxTokens: 32768, },
                  ],
                },
              }
            },
            agents: {
              defaults: {
                model: {
                  primary: "minimax/MiniMax-M2.7",
                  fallbacks: [
                    "ollama/Qwen3-Coder-Next-GGUF",
                  ]
                },
                models: {
                  "minimax/MiniMax-M2.7": { alias: "minimax" },
                  "ollama/Qwen3-Coder-Next-GGUF": { alias: "coder", params: { cache_prompt: true } },
                },
                workspace: "/home/node/.openclaw/workspaces/main",
              },
              list: [
                {
                  id: "main",
                  name: "main",
                  workspace: "/home/node/.openclaw/workspaces/main",
                  agentDir: "/home/node/.openclaw/agents/main/agent",
                },
                {
                  id: "jade",
                  name: "jade",
                  workspace: "/home/node/.openclaw/workspaces/jade",
                  agentDir: "/home/node/.openclaw/agents/jade/agent",
                },
                {
                  id: "jarvis",
                  name: "jarvis",
                  workspace: "/home/node/.openclaw/workspaces/jarvis",
                  agentDir: "/home/node/.openclaw/agents/jarvis/agent",
                },
              ]
            },
            tools: {
              "profile": "coding",
            },
            commands: {
              native: "auto",
              nativeSkills: "auto",
              restart: true,
              ownerDisplay: "raw",
            },
            session: {
              "dmScope": "per-channel-peer",
            },
            channels: {
              discord: {
                enabled: true,
                token: "{{ .discord_token }}",
                groupPolicy: "allowlist",
                guilds: {
                  "{{ .discord_server_id }}": {
                    requireMention: true,
                    users: ["{{ .discord_user_id }}"],
                  },
                },
                streaming: "off",
              }
            },
            bindings: [
              {
                agentId: "jade",
                match: {
                  channel: "discord",
                  guildId: "{{ .discord_server_id }}",
                  peer: { 
                    "kind": "channel", 
                    "id": "{{ .discord_channel_jade_id }}",
                  },
                },
              },
              {
                agentId: "jarvis",
                match: {
                  channel: "discord",
                  guildId: "{{ .discord_server_id }}",
                  peer: { 
                    "kind": "channel", 
                    "id": "{{ .discord_channel_jarvis_id }}",
                  },
                },
              },
            ],
            gateway: {
              port: 18789,
              mode: "local",
              bind: "loopback",
              auth: {
                mode: "token",
                token: "{{ .OPENCLAW_GATEWAY_TOKEN }}",
              },
              nodes: {
                "denyCommands": [
                  "camera.snap",
                  "camera.clip",
                  "screen.record",
                  "contacts.add",
                  "calendar.add",
                  "reminders.add",
                  "sms.send",
                ]
              },
            }
          }
  data:
  - secretKey: OPENCLAW_GATEWAY_TOKEN
    remoteRef:
      key: openclaw
      property: OPENCLAW_GATEWAY_TOKEN
  # Discord
  - secretKey: discord_server_id
    remoteRef:
      key: discord-common
      property: discord_server_id
  - secretKey: discord_user_id
    remoteRef:
      key: discord-common
      property: discord_user_id
  - secretKey: discord_token
    remoteRef:
      key: discord-common
      property: discord_token
  ## Agent-specific data
  - secretKey: discord_channel_jade_id
    remoteRef:
      key: discord-jade
      property: discord_channel_id
  - secretKey: discord_channel_jarvis_id
    remoteRef:
      key: discord-jarvis
      property: discord_channel_id
  # Model keys
  - secretKey: MINIMAX_API_KEY
    remoteRef:
      key: minimax-api
      property: password
