apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      version: 0.26.1
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  interval: 15m
