---
# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mmo
  namespace: flux-system
spec:
  components:
    - ../../../../../components/postgres
    - ../../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *app
      POSTGRES_REPLICAS: "1"
      POSTGRES_SIZE: 2Gi
      DRAGONFLY_REPLICAS: "1"
      DRAGONFLY_MAX_MEMORY: 512Mi
  targetNamespace: *app
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/projects/mmo/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mmo-monitoring
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: mmo
  interval: 5m
  path: ./apps/base/projects/mmo/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
