apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  targetNamespace: grafana-operator
  commonMetadata:
    labels:
      service: grafana-operator
  interval: 5m
  path: ./apps/base/grafana-operator/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: grafana
  dependsOn:
    - name: grafana-operator
  interval: 5m
  path: ./apps/base/grafana-operator/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-folders
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: grafana
  dependsOn:
    - name: grafana
  interval: 5m
  path: ./apps/base/grafana-operator/folders
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-dashboards
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: grafana
  dependsOn:
    - name: grafana
  interval: 5m
  path: ./apps/base/grafana-operator/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
