apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karpor
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: kusionstack
        namespace: flux-system
      version: 0.7.6
  interval: 15m
  commonMetadata:
    labels:
      service: *app
