# yaml-language-server: $schema=https://ctrl-research.github.io/k8s-schemas/core/namespace_v1.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
