apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  chartRef:
    kind: OCIRepository
    name: grafana-operator
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  interval: 15m
  values:
    dashboard:
      enabled: true
      annotations:
        grafana_folder: Kubernetes
      labels:
        grafana_dashboard: "1"
    serviceMonitor:
      enabled: true
