apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  targetNamespace: dragonfly-operator
  commonMetadata:
    labels:
      service: dragonfly-operator
  interval: 5m
  path: ./apps/base/dragonfly-operator/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
